### ISSUE TITLE
[BUG] Imported Encrypted SSH Key, now api is crashing

### ISSUE THREAD

**Issue by hoferbeck** [SquirrelCorporation/SquirrelServersManager#42]
**Describe the bug**
Imported a Encrypted SSH key  without the Password, now the api is crashing
** Logs **
In most cases, logs will be needed to help the debugging process
Provide here the logs output
```
[08:25:20.817] INFO (1): [WATCHER][DOCKER] - Register with configuration {"cron":"0 * * * *","watchbydefault":true,"deviceUuid":"970c715f-8e38-4421-b637-ce62d9b35afe","watchstats":true,"cronstats":"0 * * * *","watchevents":true,"socket":"/var/run/docker.sock","port":2375,"watchall":false}
    module: "watcher/docker/docker-970c715f-8e38-4421-b637-ce62d9b35afe"
/server/node_modules/ssh2/lib/client.js:261
        throw new Error(`Cannot parse privateKey: ${privateKey.message}`);
              ^

Error: Cannot parse privateKey: Encrypted private OpenSSH key detected, but no passphrase given
    at Client.connect (/server/node_modules/ssh2/lib/client.js:261:15)
    at SsmSshAgent.createConnection (/server/dist/src/integrations/docker/core/CustomAgent.js:65:18)
    at SsmSshAgent.createSocket (node:_http_agent:340:26)
    at SsmSshAgent.addRequest (node:_http_agent:288:10)
    at new ClientRequest (node:_http_client:336:16)
    at Object.request (node:http:103:10)
    at h.request (/server/node_modules/docker-modem/lib/http.js:51:52)
    at Modem.buildRequest (/server/node_modules/docker-modem/lib/modem.js:276:68)
    at /server/node_modules/docker-modem/lib/modem.js:237:12
```

**To Reproduce**
Added new host with api key and didnt provide a Password

**Expected behavior**
Not Crash / Validate in the Frontend if an Key is encrypted

**(please complete the following information):**
 - OS: Debian 12
 - Browser Firefox
 - Version 106

**Additional context**

Can you tell me how to remove the ssh key via cli as im unable to login into the WebGUI (502 Errors)

**Comment by SquirrelDeveloper** [comment]
Hi @hoferbeck , thanks for the feedback! 
This bug should have been fixed in the master version of the code, if you can try it by building the project https://squirrelserversmanager.io/docs/quickstart#build-the-project-by-yourself

**Comment by hoferbeck** [comment]
Sorry for waiting so long but the issue is now fixed with the lasted version
